# encoding: utf-8
# THIS FILE IS AUTOGENERATED!
from __future__ import unicode_literals
from setuptools import setup
setup(
    author='Kyle Lahnakoski',
    author_email='kyle@lahnakoski.com',
    classifiers=["Development Status :: 4 - Beta","Topic :: Software Development :: Libraries","Topic :: Software Development :: Libraries :: Python Modules","License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)","Programming Language :: Python :: 2.7","Programming Language :: Python :: 3.6","Programming Language :: Python :: 3.7","Programming Language :: Python :: 3.8"],
    description='More SQL!  For safely assembling SQL',
    include_package_data=True,
    install_requires=["mo-dots>=3.47.20042","mo-future>=3.47.20042","mo-logs>=3.47.20042"],
    license='MPL 2.0',
    long_description='# mo-sql\n\nMore SQL!\n\nA SQL datatype, plus a number of constants for safe SQL composition.',
    long_description_content_type='text/markdown',
    name='mo-sql',
    packages=["mo_sql"],
    url='https://github.com/klahnakoski/mo-sql',
    version='3.47.20042'
)